name: deploy production
on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

defaults:
    run:
        shell: bash
        working-directory: infra_website
    

jobs:
    pull:
        name: pull
        runs-on: self-hosted
        steps:
            - name: pull
              run: git pull --rebase
    image:
        needs: pull
        name: image
        runs-on: self-hosted
        steps:
            - name: build
              run: podman build -t ${{ github.job }} .
    deploy:
        needs: image
        name: deploy
        runs-on: self-hosted
        steps:
            - name: cleanup
              run: podman rm -f image
            - name: run-image
              run: podman run -p 3500:3500 $ENV --name image -d image